version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nextjs-app
    ports:
      - "3001:3001"
    image: anoopkarnik/turborepo-saas-boilerplate-code-nextjs-app:latest
    restart: always


